### ISSUE TITLE
Canvas code in autogenerated index.html

### ISSUE THREAD

**Issue by madmaxio** [koute/cargo-web#103]
I plan to add some style sheets, so I should you use my own index.html.
But autogenerated index.html has this code:

```
var Module = {};
        var __cargo_web = {};
        Object.defineProperty( Module, 'canvas', {
            get: function() {
                if( __cargo_web.canvas ) {
                    return __cargo_web.canvas;
                }

                var canvas = document.createElement( 'canvas' );
                document.querySelector( 'body' ).appendChild( canvas );
                __cargo_web.canvas = canvas;

                return canvas;
            }
        });
```

So the questions are:

1. Should I include the code above in my own index.html?
2. Are there any options to include style sheets without making handcoded index.html in static folder?
Because I really like the concept of autogenetared one.

**Comment by koute** [comment]
The canvas is there for Emscripten so stuff like SDL2 works; if you don't need it then you can just delete that part. The autogenerated `index.html` is mostly a placeholder though (at least right now) and it's not possible to customize it nor include custom stylesheets without replacing it altogether.

There already was an issue (https://github.com/koute/cargo-web/issues/99) about automatically including stylesheets, and, well, it's not really obvious how something like that would work. What if there are multiple stylesheets? Should it include all of them? What if they are not in the root directory? Do they have to be named in a certain way, or should it just grab any `.css` file it finds? What if someone doesn't want this behavior? All of it seems very complicated for not that much gain.

**Comment by madmaxio** [comment]
Thanx, I needed mostly canvas part clarification. This opens using custom index.hmtl.
