### ISSUE TITLE
Failes to run wasm_gc

### ISSUE THREAD

**Issue by flosse** [koute/cargo-web#108]
- rustc 1.28.0-nightly (4ecf12bf0 2018-06-02)
- cargo-web 0.6.12
- default-target = "wasm32-unknown-unknown"
```
Garbage collecting "rust-app.wasm"...
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 2', src/wasm_gc.rs:266:23
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
It happens here:

https://github.com/koute/cargo-web/blob/2b3b1ff68655e533e08f2312268a2d2ac9807f82/src/wasm_gc.rs#L266

**Comment by koute** [comment]
Sorry for the delay; I had no access to a computer for the last two weeks.

Is this still a problem? I can't reproduce it on my machine.

* rustc 1.28.0-nightly (523097979 2018-06-18)
* yew: current newest `master`, commit a67751f6f17b278e96fc883dbd488c64812045c1
