### ISSUE TITLE
Announce it somewhere

### ISSUE THREAD

**Issue by vlad20012** [koute/cargo-web#11]
Oh... guys, half of humanity really needs this tool, but it is totally ungooglable! I've just [reinvented](https://github.com/vlad20012/rust-wasm-test-runner) the wheel to solve the same problem, but then found your excellent solution. 

And yes, "stdweb" have the same problem, I [assure](https://github.com/irbis-labs/rust-webplatform) you.

**Comment by koute** [comment]
I'm afraid my solution is still very far from excellent, but thanks!

This is still such a huge work-in-progress that I don't feel like I can announce it in good faith anywhere, but if you feel like it should be then feel free to do it yourself. (:

**Comment by vlad20012** [comment]
Bury your perfectionism. It's OK to announce MVP. You can help many people by telling about this tool. And help yourself by new contributors.
Ok. I'll write a post soon.

And hmm, how can I contact you? Any messanger? I use gitter.im, for example... (and it would be cool to attach to create gitter room for stdweb and related projects)
