### ISSUE TITLE
Compiling showcase demo from yew gives  'internal error: same snippet of JS (by value) is used with two different shims; please report this!'

### ISSUE THREAD

**Issue by kjeremy** [koute/cargo-web#118]
I checked out yew (from master) and tried to build the showcase example from https://github.com/DenisKolodin/yew/tree/master/examples/showcase.  I received a panic. This is on Windows 10.
> $ RUST_BACKTRACE=1 cargo web start --target=wasm32-unknown-unknown --verbose
warning: debug builds on the wasm32-unknown-unknown are currently totally broken         forcing a release build
       Fresh unicode-xid v0.1.0
       Fresh unicode-xid v0.0.4
       Fresh quote v0.3.15
       Fresh itoa v0.4.2
       Fresh dtoa v0.4.3
       Fresh cfg-if v0.1.4
       Fresh byteorder v1.2.3
       Fresh rustc-demangle v0.1.8
       Fresh base-x v0.2.2
       Fresh iovec v0.1.2
       Fresh rand_core v0.2.1 (https://github.com/rust-lang-nursery/rand#d625b180)
       Fresh fnv v1.0.6
       Fresh discard v1.0.3
       Fresh unicode-width v0.1.5
       Fresh anymap v0.12.1
       Fresh slab v0.4.0
       Fresh bitflags v0.9.1
       Fresh strum v0.9.0
       Fresh proc-macro2 v0.4.6
       Fresh proc-macro2 v0.2.3
       Fresh synom v0.11.3
       Fresh log v0.4.3
       Fresh backtrace v0.3.9
       Fresh bytes v0.4.8
       Fresh rand_isaac v0.1.0 (https://github.com/rust-lang-nursery/rand#d625b180)
       Fresh getopts v0.2.18
       Fresh quote v0.6.3
       Fresh quote v0.4.2
       Fresh serde v1.0.70
       Fresh syn v0.11.11
       Fresh http v0.1.7
       Fresh pulldown-cmark v0.1.2
       Fresh syn v0.14.4
       Fresh syn v0.12.15
       Fresh serde_json v1.0.24
       Fresh toml v0.4.6
       Fresh bincode v1.0.1
       Fresh synstructure v0.6.1
       Fresh serde_derive v1.0.70
       Fresh strum_macros v0.9.1
       Fresh failure_derive v0.1.1
       Fresh stdweb-internal-macros v0.1.0
       Fresh stdweb-derive v0.4.0
       Fresh failure v0.1.1
       Fresh stdweb v0.4.7
       Fresh yew v0.5.0 (file:///C:/projects/test/yew)
       Fresh web_logger v0.1.0
       Fresh rand v0.5.4 (https://github.com/rust-lang-nursery/rand#d625b180)
       Fresh inner_html v0.1.0 (file:///C:/projects/test/yew/examples/inner_html)
       Fresh textarea v0.1.0 (file:///C:/projects/test/yew/examples/textarea)
       Fresh fragments v0.1.0 (file:///C:/projects/test/yew/examples/fragments)
       Fresh counter v0.1.1 (file:///C:/projects/test/yew/examples/counter)
       Fresh dashboard v0.1.0 (file:///C:/projects/test/yew/examples/dashboard)
       Fresh npm_and_rest v0.1.0 (file:///C:/projects/test/yew/examples/npm_and_rest)
       Fresh timer v0.1.0 (file:///C:/projects/test/yew/examples/timer)
       Fresh mount_point v0.1.0 (file:///C:/projects/test/yew/examples/mount_point)
       Fresh custom_components v0.1.0 (file:///C:/projects/test/yew/examples/custom_components)
       Fresh crm v0.1.0 (file:///C:/projects/test/yew/examples/crm)
       Fresh todomvc v0.1.0 (file:///C:/projects/test/yew/examples/todomvc)
       Fresh large_table v0.1.0 (file:///C:/projects/test/yew/examples/large_table)
       Fresh two_apps v0.1.0 (file:///C:/projects/test/yew/examples/two_apps)
       Fresh game_of_life v0.1.3 (file:///C:/projects/test/yew/examples/game_of_life)
       Fresh showcase v0.1.0 (file:///C:/projects/test/yew/examples/showcase)
    Finished release [optimized] target(s) in 0.32s
    Garbage collecting "showcase.wasm"...
    Processing "showcase.wasm"...
thread 'main' panicked at 'internal error: same snippet of JS (by value) is used with two different shims; please report this!', src\wasm_inline_js.rs:105:17
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

**Comment by koute** [comment]
It looks like it's an issue in `rustc` and/or LLVM; here's what the `.wasm` looks like:

```
  (data (i32.const 1058676) "")
  (data (i32.const 1058676) "Module.STDWEB_PRIVATE.decrement_refcount( $0 );\00")
```

So basically what happens here is that we have two duplicate data entries with the same address, so when `cargo-web` searches for the JS snippet with address "1058676" it finds the first entry and treats that as the snippet for that given `js!` invocation, and coincidentally there were actually two such snippets so it panicked.

**Comment by koute** [comment]
I've pushed a workaround for this issue. @kjeremy: Could you grab the current `cargo-web` from `master` and verify that it also fixes the issue for you?

**Comment by kjeremy** [comment]
It seems to fix that specific issue but I get intermittent failures. I have to run `cargo web start` multiple times sometimes to get a successful build.

**Comment by koute** [comment]
Yes, I've also been getting that. It looks like another Rust bug, unfortunately. ):

**Comment by bluejekyll** [comment]
If it helps, I just encountered this, example branch: https://github.com/bluejekyll/kp-chart/tree/duplicate_shim

If this line is commented out, it goes away: https://github.com/bluejekyll/kp-chart/blob/duplicate_shim/src/web/people.rs#L35
