### ISSUE TITLE
cargo web fails to build project intermittently

### ISSUE THREAD

**Issue by kjeremy** [koute/cargo-web#119]
Occasionally `cargo web start` fails and has to be run multiple times before a successful build occurs. See https://github.com/koute/cargo-web/issues/118#issuecomment-405989881

**Comment by koute** [comment]
Did this fix itself? If not please reopen.

**Comment by Itanq** [comment]
**I can't build the net2 project with cargo-web, but I can build the net2 project with cargo.** 
The error information as following:
```
zmant@zmant-PC:~/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/net2-0.2.33$ cargo-web build --release
   Compiling cfg-if v0.1.9
   Compiling net2 v0.2.33 (/home/zmant/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/net2-0.2.33)
error[E0432]: unresolved import `sys`
  --> src/tcp.rs:18:5
   |
18 | use sys::c;
   |     ^^^ maybe a missing `extern crate sys;`?
error[E0432]: unresolved import `sys`
  --> src/udp.rs:18:5
   |
18 | use sys::c;
   |     ^^^ maybe a missing `extern crate sys;`?
error[E0432]: unresolved import `sys`
  --> src/socket.rs:22:5
   |
22 | use sys;
   |     ^^^ no `sys` in the root
error[E0432]: unresolved import `sys`
  --> src/socket.rs:23:5
   |
23 | use sys::c;
   |     ^^^ maybe a missing `extern crate sys;`?
error[E0432]: unresolved import `sys`
  --> src/ext.rs:19:5
   |
19 | use sys;
   |     ^^^ no `sys` in the root
error[E0432]: unresolved import `sys`
  --> src/ext.rs:20:5
   |
20 | use sys::c;
   |     ^^^ maybe a missing `extern crate sys;`?
error[E0412]: cannot find type `c_int` in this scope
.........
error[E0046]: not all trait items implemented, missing: `send`, `recv`
   --> src/ext.rs:970:1
    |
621 |     fn send(&self, buf: &[u8]) -> io::Result<usize>;
    |     ------------------------------------------------ `send` from trait
...
628 |     fn recv(&self, buf: &mut [u8]) -> io::Result<usize>;
    |     ---------------------------------------------------- `recv` from trait
...
970 | impl UdpSocketExt for UdpSocket {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `send`, `recv` in implementation

error: aborting due to 243 previous errors
Some errors occurred: E0046, E0412, E0422, E0425, E0432.
For more information about an error, try `rustc --explain E0046`.
error: Could not compile `net2`.

To learn more, run the command again with --verbose.
error: build failed
```
**Probability of recurrence：100%.**
Any one can help me? thanks very much!!!

**Comment by Pauan** [comment]
@Itanq When you say that you *can* build it with `cargo`, does that mean you tried it with `cargo build --target wasm32-unknown-unknown`?

**Comment by Itanq** [comment]
Hi @Pauan, Thanks your reply, I has tried it with c`argo build --target wasm32-unknown-unknown`, It aslo can't build, such as cargo-web. Could it be a problem with wasm? How can I resolved it? Thank you very much!

**Comment by Pauan** [comment]
Yes, in that case it's not a problem with cargo-web.

The issue is that `net2` is using network APIs which don't exist in the web browser. It's a problem with the web browser, not Rust, so there's nothing that can be done to fix it.

So, you cannot use `net2`, instead you'll need to use the web browser APIs, such as [`XmlHttpRequest`](https://docs.rs/stdweb/0.4.17/stdweb/web/struct.XmlHttpRequest.html), [`WebSocket`](https://docs.rs/stdweb/0.4.17/stdweb/web/struct.WebSocket.html), or [`FileReader`](https://docs.rs/stdweb/0.4.17/stdweb/web/struct.FileReader.html).

**Comment by Itanq** [comment]
Ok, got it. Thanks for your answer！
