### ISSUE TITLE
How to deploy release build?

### ISSUE THREAD

**Issue by Boscop** [koute/cargo-web#121]
```
> cargo web deploy
warning: debug builds on the wasm32-unknown-unknown are currently totally broken
         forcing a release build
    Finished release [optimized] target(s) in 0.60s
    Garbage collecting "frontend.wasm"...
    Processing "frontend.wasm"...
    Finished processing of "frontend.wasm"!
The `frontend` was deployed to "D:\\projects\\myproject\\target\\deploy"!
```
But I want to pass `--release` so that when this issue is fixed and release builds work, it will build with `-release` and wont accidentally deploy a debug build. So I tried `cargo web deploy --release` but:
```
> cargo web deploy --release
   Compiling stdweb v0.4.8
error: Could not compile `stdweb`.

error: build failed
```
rustc.exe crashes every time:

![image](https://user-images.githubusercontent.com/535593/43057398-54f7268c-8e42-11e8-833c-a3081026b71c.png)

Like in https://github.com/koute/cargo-web/issues/120

But why does it work without `--release` then, if that command actually does a release build? Shouldn't it behave the same then?

I also noticed the first time I passed `--release` it compiled all the deps again, even though the normal build should have already built the release versions of the deps, right?

**Comment by Pauan** [comment]
Sounds like https://github.com/koute/stdweb/issues/249

**Comment by Boscop** [comment]
I'm on Win 8.1 btw.

**Comment by koute** [comment]
> But why does it work without `--release` then, if that command actually does a release build? Shouldn't it behave the same then?

There is one difference between `--target=wasm32-unknown-unknown --release` and just `--target=wasm32-unknown-unknown` - compiling without `--release` emits debug info by default.
