### ISSUE TITLE
Provide generate multiple js files.

### ISSUE THREAD

**Issue by ghost** [koute/cargo-web#13]
generate multiple js files. each html files can han one or other js file.  Currently supported?
another Currently supported SPA?

**Comment by koute** [comment]
It's not currently supported; AFAIK that's how the Rust compiler/Emscripten does it, and I'm not sure if I can do anything about it.

When Rust's native wasm backend stabilizes I'll switch to that by default and then such requests will be possible.

**Comment by krircc** [comment]
@koute thanks, it’s cool like you say

**Comment by jice-nospam** [comment]
Right now, cargo can generate/run several binaries with a [workspace] and several [[bin]] and the --bin parameter. This still isn't possible with current wasm32-unknown-unknown compiler target?

**Comment by koute** [comment]
@jice-nospam Well, if you have something like this in your `Cargo.toml`:

```
[[bin]]
name = "aaa"
path = "src/aaa/main.rs"

[[bin]]
name = "bbb"
path = "src/bbb/main.rs"
```
then launching `cargo web build` **will** build them both, regardless of which target you're using. But they will still be treated independently. (e.g. `cargo web start` or `cargo web deploy` will only pick and use one.)
