### ISSUE TITLE
hit recursion limit in macro but cargo-web didn't report it

### ISSUE THREAD

**Issue by kjeremy** [koute/cargo-web#136]
`cargo web build` outputs:
> ==== Triggering `cargo build` ====
warning: debug builds on the wasm32-unknown-unknown are currently totally broken
         forcing a release build
   Compiling yew-test v0.1.0 (file:///C:/projects/test/yew-test)
error: Could not compile `yew-test`.

`cargo build` outputs:
> Compiling yew-test v0.1.0 (file:///C:/projects/test/yew-test)
error: recursion limit reached while expanding the macro `html_impl`
   --> src\components\network_config.rs:84:9
    |
84  | /         html! {
85  | |             <form class="uk-form-horizontal uk-margin-small",>
86  | |                 <div class="uk-margin",>
87  | |                     <label class="uk-form-label", for="ip-address",>{"IP Address"}</label>
...   |
110 | |             </form>
111 | |         }
    | |_________^
    |
    = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

error: Could not compile `yew-test`.

**Comment by koute** [comment]
Thanks for the report!

Hmm... looks like I can't really do anything about this as it's an issue with `cargo` itself.

I've created a new issue here: https://github.com/rust-lang/cargo/issues/5992
