### ISSUE TITLE
cargo-web swallows logging from proc macros and says the build failed

### ISSUE THREAD

**Issue by ForsakenHarmony** [koute/cargo-web#138]
was writing a proc macro and whenever I printed something I just saw

```
   Compiling engine_codegen v0.1.0 (file:///C:/Users/harmony/Code/Rust/wasm3d/engine_codegen)
   Compiling wasm3d v0.1.0 (file:///C:/Users/harmony/Code/Rust/wasm3d)
error: Could not compile `wasm3d`.
```

normal builds were fine

**Comment by koute** [comment]
This is, AFAIR, normal. If I need to print something out from a procedural macro for debugging purposes I just use `panic!( "{:?}", value );`.

**Comment by ForsakenHarmony** [comment]
But if I use `cargo build` I get the output and it says the build was successful

**Comment by koute** [comment]
Try using `cargo build --message-format=json` and see if it builds. (:

Since we're wrapping `cargo` we need to use `--message-format=json`, and unfortunately when triggered in this mode `cargo` sometimes behaves in a subtly different way than it would by default.
