### ISSUE TITLE
static files not being served

### ISSUE THREAD

**Issue by p1g30n** [koute/cargo-web#14]
Hi, I can't get static files to be served, no matter what path I try, is there anything that isn't in documentation I should be aware of to get it working?

**Comment by koute** [comment]
It should work. On what OS are you? Does the [stdweb's todomvc example](https://github.com/koute/stdweb/tree/master/examples/todomvc) work for you?

**Comment by p1g30n** [comment]
Hey, I'm on osx, stdweb example works for me but I just realized that I probably misunderstood the line "will be served alongside your application", I was trying to use File::open() with files in the static directory, I guess I have to use a http request to the local file instead?

**Comment by koute** [comment]
Yes, that's correct; they will be served by the HTTP server. You can either make an HTTP request from your code (either by using raw AJAX calls from inside an `js!` call as we don't have bindings for that yet, or maybe possibly with [stdweb-io](https://github.com/CryZe/stdweb-io/)) or you can move those files somewhere else in your source tree and use [`include_bytes!`](https://doc.rust-lang.org/std/macro.include_bytes.html) or [`include_str`](https://doc.rust-lang.org/std/macro.include_str.html).

*Technically* Emscripten supports hooking into `File::open`, but there are no plans to support that. (In general I'd like to scrap Emscripten *completely* once Rust's native wasm backend matures.)

**Comment by p1g30n** [comment]
Thanks for the info. Will check out stdweb-io. And thanks for cargo-web in general it's very practical to use.
