### ISSUE TITLE
deploy command crashes if no suitable target

### ISSUE THREAD

**Issue by lukaslueg** [koute/cargo-web#148]
https://github.com/koute/cargo-web/blob/39ce0fe10a18b0551d91360fde27aadc6dcbd680/src/cmd_deploy.rs#L25

We can get `0.6.19` to crash on this line if the target is `asmjs-unknown-emscripten` and there is no `Bin`-target. The call to `project.target_or_select(...)`above yields no results and the index operation fails with `thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0'`

**Comment by koute** [comment]
Fixed on `master`; thanks for the report!
