### ISSUE TITLE
LLVM ERROR: Binary operator type not yet supported for integer types larger than 64 bits

### ISSUE THREAD

**Issue by svenstaro** [koute/cargo-web#152]
I get this error when trying to compile [my project](https://github.com/svenstaro/genact) using cargo-web 0.6.19 and 0.6.20:

    LLVM ERROR: Binary operator type not yet supported for integer types larger than 64 bits

Full log attached: [build.log](https://github.com/koute/cargo-web/files/2604934/build.log)

System information: Arch Linux gcc 8.2.1, clang 7, rust 1.32.0-nightly. It doesn't matter when I use the emscripten/binaryen versions that cargo-web wants to download or whether I use my system versions.

There's an issue in emscripten that looks like it: https://github.com/kripken/emscripten/issues/3789

What I do: `cargo-web build --release`

My **Web.toml**:

    default-target = "wasm32-unknown-emscripten"
    
    [target.emscripten]
    link-args = ["-s", "EMTERPRETIFY=1", "-s", "EMTERPRETIFY_ASYNC=1"]

I don't even know whether this is the right place to post this but I've got to start _somewhere_.

**Comment by koute** [comment]
This looks like something somewhere in your crate graph is using the `i128`/`u128` type.

I had this problem myself before with `serde` but managed to track it down and fixed it by having `serde` disable the support for `i128` on Emscripten by default.

So we'd need to figure out which crate exactly breaks the compilation here. I see you've upgraded to `rand` 0.6 - perhaps that's your culprit? I'd start with reverting that and seeing if it compiles. If that won't help then reverting to a previous `Cargo.lock` and quickly trying to bisect the updated dependencies might be a good idea.

**Comment by svenstaro** [comment]
Super fine idea, I'll have a look.

**Comment by svenstaro** [comment]
Alright so it _is_ due to rand 0.6! And rand 0.6 did some SIMD stuff but that appears to be turned off by default. Bit clueless here.

**Comment by koute** [comment]
Probably due to `i128` support.

From their changelog:

```
## [0.6.0] - 2018-11-14
...
- Support for `i128` and `u128` is automatically enabled for Rust >= 1.26. This
  renders the `i128_support` feature obsolete. It still exists for backwards
  compatibility but does not have any effect. This breaks programs using Rand
  with `i128_support` on nightlies older than Rust 1.26. (#571)
```

So it looks like it's turned on by default.

**Comment by svenstaro** [comment]
I saw that but don't know how to turn it off.

**Comment by koute** [comment]
Can you experimentally just comment out the body of `main` in `rand`'s `build.rs`, and recompile your project with that as a dependency? (Please note that there are three `build.rs`es there in total.)

That should help confirm if that's indeed the issue, and if it is this needs to be properly fixed in `rand` by disabling `i128` support by default on Emscripten targets.

**Comment by svenstaro** [comment]
Sorry for the long silence. Your suggestion makes it work!

**Comment by svenstaro** [comment]
Any idea where to go from here? I reported an issue upstream.

**Comment by svenstaro** [comment]
Not a cargo-web problem at all and we're fixing this over in rand for now. Perhaps at some point upstream will fix this in emscripten. For the time being, the fix in rand is good enough. Thanks.
