### ISSUE TITLE
How to deploy to a different dir than target/deploy?

### ISSUE THREAD

**Issue by Boscop** [koute/cargo-web#155]
For heroku I need to include my frontend's static assets in the git repo, which means all the files that `cargo web deploy` generates. Since I don't want to include the `target` dir in my git repo, how can I output to a custom dir?

**Comment by rickyhan** [comment]
You can copy the files in `target/deploy` to your deploy directory.

**Comment by koute** [comment]
0.6.22 has `-o`/`--output`
