### ISSUE TITLE
Add custom headers to integrated web server

### ISSUE THREAD

**Issue by MattiasFestin** [koute/cargo-web#161]
Hi.

I run my api on a diffrent port (and crate). 
My app cargo-web app can't communicate with my api because it is on a diffrent origin.
So for it to be able to communicate I need to set CORS headers. (More info at https://www.w3.org/TR/cors/#access-control-allow-origin-response-header)

A command line argument or a property in the Web.toml that allows setting custom headers would solve this.

**Comment by koute** [comment]
You mean that `cargo web start` should serve files with `Access-Control-Allow-Origin: *`? Since the integrated web server is meant only for development I'd be fine with just having that in there by default.  (Unless you can foresee some potential problems with that?)

**Comment by MattiasFestin** [comment]
No, I think that sounds like a good solution.

I just thought that having the option to set your own headers would solve potential other problems.
But you are right about it just being for development.
The header `Access-Control-Allow-Origin:* ` would solve my problem.

The only reason I thought for setting custom headers is if someone needs sending custom headers from the browser to a different origin.
Then they must be whitelisted by: `Access-Control-Allow-Headers: X-CUSTOM-HEADER` and `Access-Control-Request-Headers: X-CUSTOM-HEADER`. 
 `Access-Control-Allow-Headers` is for the preflight OPTIONS request and `Access-Control-Request-Headers` is for the actual request.
I could not find any in the specification that allows wildcards for `Access-Control-Allow-Headers` unfortunately. So it must be set explicit for every header the developer wants to send,

**Comment by koute** [comment]
I've added the `Access-Control-Allow-Origin: *` header on `master`; it should be available in the next `cargo-web` release this week.

**Comment by koute** [comment]
Released as 0.6.22.

Since this should solve your original problem I'm closing this issue. If someone actually needs custom headers in the future then please reopen or make a new issue. I'm not against the idea, however we'd need some minimal design work as to figure out the best way to actually configure those custom headers.
