### ISSUE TITLE
`cargo web start` adds trash in the served version of app.js

### ISSUE THREAD

**Issue by jatentaki** [koute/cargo-web#164]
I'm revisiting my project from January 2018, so I am trying to build it using a significantly newer version of rust and cargo web. What I found is that if I execute `cargo web start --target=wasm32-unknown-unknown`, I
1. get the producers error already mentioned in #153
2. the `app.js` file served by the server is polluted with some trash in js import function definitions. If I check `/target/deploy/app.js` the trash is not there and if I manually instruct my code to grab the scripts from that location, it works.

The section of `/target/deplay/app.js` looks like this:

    const __imports = {
        env: {
            "__extjs_de942ef9ccd064c41dc92d5b5bf83c61aeb00278": function($0) {
                Module.STDWEB.increment_refcount( $0 );
            },
            "__extjs_d8a439451216bbc6cd9f3012f189d2ad6a2e9459": function($0) {
                Module.STDWEB.decrement_refcount( $0 );
            },
            "__extjs_836c2811a14e29305c7c49cf4d5cc4751ae98657": function($0) {
                Module.STDWEB.from_js($0, (function(){console.log ("Schedule is not initalized");})());
            },

Whereas the one served by the server looks like this:

    return {
        imports: {
            env: {
                "__extjs_01963e4faab2f936135d8ef47199eb59bbf70258": function($0) {
                Module.STDWEB.decrement_refcount( $0 );():
            },
            "__extjs_03b83eed9801e5ea524685470676c61dd8f37451": function($0) {
                Module.STDWEB.from_js($0, (function(){console.log ("Schedule is not initalized");})());Uint8Array load error:
            },
            "__extjs_0ec0da73f8436ea91266ef3dd05ede642cccacab": function($0, $1, $2, $3, $4) {
                $1 = Module.STDWEB.to_js($1);$2 = Module.STDWEB.to_js($2);$3 = Module.STDWEB.to_js($3);$4 = Module.STDWEB.to_js($4);Module.STDWEB.from_js($0, (function(){Module.exports.initializeSchedule = ($1); Module.exports.dijkstraPath = ($2); Module.exports.getNodes = ($3); Module.exports.initPackage = ($4);})());PathNodeftsExpected  arguments, got
            }, 

Note the invalid javascript syntax like `():` or `Uint8Array load error:`. What could be the cause?

**Comment by koute** [comment]
Which version of `stdweb` are you using? Old versions (0.3.x and older) are broken on `wasm32-unknown-unknown` when paired with a recent Rust version, and will result in corrupted JS snippets like the one you've got. (This is due to the way how old Rust used to generate data sections vs how the new Rust does it.)

**Comment by jatentaki** [comment]
```
jatentaki@drozd:~$ cargo web --version
cargo-web 0.6.21

jatentaki@drozd:~$ rustc --version
rustc 1.32.0-nightly (4a45578bc 2018-12-07)
```

So it doesn't seem to be that reason.

**Comment by koute** [comment]
@jatentaki So did you figure out your issue? Is it still there when you're using the newest `cargo-web` and the newest `stdweb`? (Be sure to also delete your `Cargo.lock`.)

**Comment by jatentaki** [comment]
Yes, sorry, I was busy. I forgot I had to delete `Cargo.lock` - now there is no trash in the file anymore but my application doesn't work either. The rust module is loaded, as reported in browser console, but callbacks are not being triggered. It's most likely the kind of breakage to be expected due to upgrading all dependencies after almost a year, I'll open separate issues if that's anything that may be of interest to you.
