### ISSUE TITLE
crash when there's a println! in proc macros

### ISSUE THREAD

**Issue by NeverGivinUp** [koute/cargo-web#168]
I used println! macros calls (for debugging) in a procedural macro I wrote for enums. rustc just prints the messages. cargo web crashes without an error message.

**Comment by koute** [comment]
Unfortunately there is nothing I can do about this AFAIK. `cargo-web` launches `cargo` with `--message-format json` and it expects only JSON payloads on the stdout, so if you try to print something out it will try to parse that as JSON and fail.

For debugging I'd recommend either panicking or writing to a file. Maybe even `eprintln!` would work (`cargo-web` treats stderr as text and prints it out as-is); I don't remember.
