### ISSUE TITLE
Cargo web build as part of a larger workspace

### ISSUE THREAD

**Issue by ApoorvaJ** [koute/cargo-web#173]
My project consists of two components. The directory tree looks like this:

    ├── Cargo.lock
    ├── Cargo.toml
    ├── client
    │   ├── Cargo.toml
    │   └── src
    │       └── main.rs
    └── server
        ├── Cargo.toml
        └── src
            └── main.rs

The top-level `Cargo.toml` is simply a workspace:
```
[workspace]
members = [ "server", "client" ]`
```
`client` is an [stdweb](https://github.com/koute/stdweb) project, which needs to be built using the Cargo subcommand `cargo web build`.

The `server` is a [hyper](https://hyper.rs/) server and is compiled as usual, using `cargo build`.

I want the whole workspace to build correctly when I simply issue a top-level `cargo build` command. Is this possible right now? If yes, how?

**Comment by koute** [comment]
You mean both the server and the client? That won't work currently - you need to build both separately.

You can always make yourself a simple script to do it for you, or use something like `cargo-make`.

**Comment by ApoorvaJ** [comment]
Thank you for the quick reply. :)

Yup, I meant the server and the client, both built using a single command. This is useful because they both depend on a third library (which I skipped in my original question, for brevity), and having a single build command is an easy way to make sure everything is synced.

Currently I am using a shell script to do this, so feel free to close this issue. However in the longer run, it would be super useful to have a better workflow for combining stdweb with a more complex server environment.

**Comment by koute** [comment]
Yes, while it might be nice I think a deeper integration is *probably* out of scope here as there are just way too many ways people can structure their projects, and even `cargo` itself doesn't support this (you need to call `cargo` twice if you want to build for two different targets). We already have enough trouble supporting all of the purely client-side use cases people have. (:
