### ISSUE TITLE
Enable compression when serving 

### ISSUE THREAD

**Issue by wathiede** [koute/cargo-web#180]
Considering wasm files are often large, it would be nice to have the contents compressed by the server.  I'm happy to send a pull request if this is a useful feature.  

Design question: automatically compress based on Accept-Encoding from the request, or flag guard automatically compressing based on Accept-Encoding?

**Comment by koute** [comment]
Sorry for the late reply.

I appreciate the interest, however I don't think this feature is actually desirable. (: `cargo web start` is *not* meant to be used in production - it's only meant for development, so I don't really a use case here for supporting compression.

Thanks!
