### ISSUE TITLE
Doesn't work as cargo subcommand

### ISSUE THREAD

**Issue by kuviman** [koute/cargo-web#186]
If I try to install current `master` version with `cargo install --git https://github.com/koute/cargo-web cargo-web`, using as cargo subcommand is failing:

```
$ cargo web --version
error: Found argument 'web' which wasn't expected, or isn't valid in this context

USAGE:
    cargo-web <SUBCOMMAND>

For more information try --help
```

I think this was broken while moving to `structopt` in #172

**Comment by koute** [comment]
Oops. Fixed!

Thanks for the report!
