### ISSUE TITLE
cargo web start triggers multiple successive rebuilds

### ISSUE THREAD

**Issue by dmit** [koute/cargo-web#187]
So this might affect some more than others, depending on their workflow. I have my editor configured to run rustfmt on each save. The way this is implemented, it causes a quick succession of `notify` events in `cargo web start`. Since the events are of multiple different types (writes, renames, removes), `notify`'s debouncing does nothing to help here. In case of a clean build it's merely a mild annoyance - only the first rebuild takes serious time and the rest only cost ~200ms and a couple extra lines of logs each thanks to incremental building. But if there are build errors the situation becomes much worse.

My proposed solution, and one I have successfully implemented in a local branch, is this: upon receiving a filesystem event that should trigger a rebuild, `cargo web start` waits an additional 500ms to see if any significant follow-up events show up. If an event is received within that window that should trigger a rebuild, the deadline for additional follow-up events is moved forward to current time + 500ms.

Would you be interested in a PR for this?

**Comment by koute** [comment]
Sounds good to me!
