### ISSUE TITLE
FreeBSD build: Please consider updating openssl

### ISSUE THREAD

**Issue by igalic** [koute/cargo-web#189]
When trying to install this package? crate? thingie… on FreeBSD, i ran into the following issue:

https://github.com/sfackler/rust-openssl/issues/1108

by updating the openssl dependency to one that includes this fix, https://github.com/alexcrichton/openssl-src-rs/pull/22 it would be possible to easily build.

**Comment by koute** [comment]
Updated `openssl-sys` on `master`. If all tests pass I'll try to release a new version tomorrow.

**Comment by igalic** [comment]
Looking at the one [failed job on Travis](https://travis-ci.org/koute/cargo-web/jobs/529023386), it seems to be an unrelated network hick-up.

**Comment by koute** [comment]
Released as 0.6.25
