### ISSUE TITLE
Alignment and segmentation faults with wasm32-unknown-emscripten

### ISSUE THREAD

**Issue by tanis2000** [koute/cargo-web#190]
I'm struggling getting a simple project to compile with cargo web for the browser through emscripten (target wasm32-unknown-emscripten)

I posted about it there: https://users.rust-lang.org/t/rust-emscripten-leading-to-an-alignment-error/28700/1

I'm using the rust-sdl2 crate that in turn has C bindings to SDL2, but I'm also telling Emscripten to use its own port of the library (-s USE_SDL=2).

The main issue is that it looks like the memory is being corrupted because calling into any of the SDL2 functions is either leading to alignment faults or segmentation faults. It doesn't happen all the time but it does happen sooner or later (more sooner than later) during the application lifecycle.

I created a simple prototype there:
https://github.com/tanis2000/rust-sdl2-wasm

The rust-sdl2 dependency is pointing at my local copy because I made some little changes to make it compile for wasm, but they've been merged upstream so you can as well point it to the master branch of its git repo.

The actual error is the following: 

```
Uncaught abort("alignment fault") at Error
    at jsStackTrace (http://localhost:8000/main.js:1667:13)
    at stackTrace (http://localhost:8000/main.js:1684:12)
    at abort (http://localhost:8000/main.js:11888:44)
    at alignfault (http://localhost:8000/main.js:1053:3)
    at SAFE_HEAP_LOAD_i32_4_4 (wasm-function[171210]:39)
    at __ZN4core4cell13Cell_LT_T_GT_3get17ha7292d0f274620b2E (wasm-function[3605]:45)
    at __ZN5alloc2rc8RcBoxPtr6strong17h9d76bc796af30b74E (wasm-function[1084]:51)
    at __ZN5alloc2rc8RcBoxPtr10inc_strong17h974f8b274d2ef40bE (wasm-function[1089]:36)
    at __ZN61__LT_alloc__rc__Rc_LT_T_GT__u20_as_u20_core__clone__Clone_GT_5clone17h42ec3c5edf9a6750E (wasm-function[1102]:36)
    at dynCall_ii (wasm-function[5737]:14)
```

I'm really struggling finding the source of the problem. I've been using Emscripten with SDL2 and plain C in other projects and I've never had any similar issues, so any help would be really appreciated.

**Comment by koute** [comment]
Interesting. I've never seen such an error. It looks however like either an issue with `rustc` or with Emscripten. I wonder - have you tried using a more recent Emscripten version? (The one `cargo-web` fetches might be a bit stale as I haven't updated it in a while.)

**Comment by tanis2000** [comment]
How do I know if cargo web is using my local version of Emscripten or if it's actually getting one on its own? I'm on macOS and I've got Emscripten 1.38.32 installed through homebrew.

**Comment by tanis2000** [comment]
@koute I narrowed down this issue further.. it's happening only if you call unsafe code in the main loop. As soon as you call some unsafe code, like simple OpenGL calls, it starts corrupting. I wonder why though.. any idea who I could get in touch with to talk about it? I'm ruling out Emscripten from the equation as all C code is unsafe by nature so I guess it's not Emscripten's fault. 
It might be something with the way the Rust compiler writes those unsafe calls before passing that code to Emscripten?

**Comment by tanis2000** [comment]
BTW I've updated the test project at https://github.com/tanis2000/rust-sdl2-wasm and now it clearly shows signs of corruption if you look run it and look at the browser's console.

**Comment by tanis2000** [comment]
I managed to fix the issue, thanks to Michael Fairley and it looks like I need to store the closure on the heap to avoid stack-allocated memory being freed and thus leading to undefined behavior and memory corruption.
I've updated the sample project with the correct code in case anyone needs it.
