### ISSUE TITLE
'sandbybridge' is not a recognized processor for this target

### ISSUE THREAD

**Issue by PhilipDaniels** [koute/cargo-web#191]
Hi,

Newbie user here. I am using `cargo-web` to start a very simple game with https://github.com/ryanisaacg/quicksilver - I followed their install instructions for cargo web. When I run `cargo web deploy` I get several hundred warnings of the form

```
...
'sandybridge' is not a recognized processor for this target (ignoring processor)
'sandybridge' is not a recognized processor for this target (ignoring processor)
'sandybridge' is not a recognized processor for this target (ignoring processor)
...
```

Despite this, it seems to deploy and run correctly.

Any clues as to where this is coming from and is there anything I can do to fix it?

**Comment by koute** [comment]
I've never seen this before. Which version of Rust are you using? Can you perhaps try a different one and see if it makes a difference?

**Comment by PhilipDaniels** [comment]
I was using stable:

```
$ rustc --version
rustc 1.34.0 (91856ed52 2019-04-10)
[linux] phil@plato ~
$ cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)
```

I just did a `rustup self update` and `rustup update`. The error still happens on both stable and nightly. For the record, stable is now at

```
$ rustc --version
rustc 1.35.0 (3c235d560 2019-05-20)
[linux] phil@plato ~/repos/quicksilver
$ cargo --version
cargo 1.35.0 (6f3e9c367 2019-04-04)

```

and nightly is now at

```
$ rustc --version
rustc 1.37.0-nightly (721268583 2019-05-28)
[linux] phil@plato ~/repos/quicksilver
$ cargo --version
cargo 1.37.0-nightly (545f35425 2019-05-23)
```

The beginning of `cargo web deploy` says

```
$ cargo web deploy
'sandybridge' is not a recognized processor for this target (ignoring processor)
'sandybridge' is not a recognized processor for this target (ignoring processor)
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'
   Compiling libc v0.2.55
```

**Comment by PhilipDaniels** [comment]
I found the cause of this. I have `export RUSTFLAGS="-C target-cpu=native"` in my .bashrc. This has not been a problem in the past because I have only done desktop development for myself.

But given the target triple of `wasm32-unknown-unknown` that explains the warnings! Unsetting RUSTFLAGS causes the warnings to disappear. I think everything is working as designed. I'll close this issue; I'll leave it up to you if you think it is worth calling out in the documentation, but I suspect that anybody that comes across this problem in the future will find this issue via Google search.

**Comment by koute** [comment]
Good to know!

Perhaps it would be worthwhile to report this as a `rustc` issue? `-C target-cpu=native` doesn't really make any sense when cross compiling, so at least the warning should be less confusing.
