### ISSUE TITLE
Tag releases in git

### ISSUE THREAD

**Issue by kpcyrd** [koute/cargo-web#20]
I'm interested in packaging this application. To do that I would need you to create tags when releasing a new version. This causes github to create a .tar.gz for those tags that I can use to build the package. :)

**Comment by koute** [comment]
Created tag `0.4.0`. (:

**Comment by kpcyrd** [comment]
Thanks, here you go https://aur.archlinux.org/packages/cargo-web/

**Comment by koute** [comment]
Thanks! (:
