### ISSUE TITLE
Static files aren't updated when using --output

### ISSUE THREAD

**Issue by nic-hartley** [koute/cargo-web#203]
Bash script to repro, if you have cargo-web already installed:

```bash
cargo new test-project
cd test-project
echo 'fn main() {}' > src/main.rs
mkdir static
echo 'foo' > static/foo
cargo web deploy --output docs/
OLD="$(cat docs/foo)"
echo 'bar' >> static/foo
cargo web deploy --output docs/
NEW="$(cat docs/foo)"
[ "$OLD" == "$NEW" ] && echo "Bug repro'd." || echo "Bug not reproduced!"
```

The equivalent without `--output` works exactly as you'd expect it to.

If you manually delete the output directory, the files are correctly copied back in.

Versions:

- `cargo web --version`: 0.6.26
- `cargo --version`: 1.36.0
- `rustc --version`: 1.36.0

**Comment by nic-hartley** [comment]
After doing some digging, this [seems intentional](https://github.com/koute/cargo-web/blob/6f1b72e547ae4e365174e5a8db47f87bd8751dd9/src/cmd_deploy.rs#L48) ([added here, as-is, with no explanation](https://github.com/koute/cargo-web/commit/67baee3057d596bdc4454003a2d13b9b9bbc0ba1)), which makes no sense to me. I'm curious to hear what the reasoning was for writing it like this while documenting it in a way that implies the correct behavior occurs.

**Comment by nic-hartley** [comment]
Quick, relatively dirty fix to this bug:

```
diff --git a/src/cmd_deploy.rs b/src/cmd_deploy.rs
index 5433561..7ab6243 100644
--- a/src/cmd_deploy.rs
+++ b/src/cmd_deploy.rs
@@ -34,18 +34,9 @@ pub fn command_deploy(build_args: BuildArgs, directory: Option<PathBuf>) -> Resu
     let deployment = Deployment::new( package, target, &result )?;
 
     let is_using_default_directory;
-    let directory = match directory {
-        Some( directory ) => {
-            is_using_default_directory = false;
-            directory
-        },
-        None => {
-            is_using_default_directory = true;
-            project.target_directory().join( "deploy" )
-        }
-    };
+    let directory = directory.unwrap_or_else( || project.target_directory().join( "deploy" ) );
 
-    if directory.exists() && is_using_default_directory {
+    if directory.exists() {
         let entries = fs::read_dir( &directory ).map_err( |error| Error::CannotRemoveDirectory( directory.clone(), error ) )?; // TODO: Another error?
         for entry in entries {
             let entry = entry.expect( "cannot unwrap directory entry" );
```

**Comment by tiziano88** [comment]
I was also puzzled by this and was just about to open an issue about it. I guess a possible reason for the current behaviour is to prevent accidental invocations with incorrect values of `output` from deleting the content of the target directory. For instance, running `cargo web deploy --output=$HOME` would delete everything in the home folder, which may not be what the user intended. @koute is this the rationale behind that? If so, it's probably worth documenting both in the code and in the help message.

**Comment by koute** [comment]
> I was also puzzled by this and was just about to open an issue about it. I guess a possible reason for the current behaviour is to prevent accidental invocations with incorrect values of `output` from deleting the content of the target directory. For instance, running `cargo web deploy --output=$HOME` would delete everything in the home folder, which may not be what the user intended. @koute is this the rationale behind that?

Correct. If the user doesn't specify an `--output` then we currently do something that's essentially an `rm -Rf` since we know that we're doing that on the default output path, however it would be very dangerous to do that with an arbitrary, user-specified `--output`. If you *really* want to get rid of that directory you can always run `rm -Rf` yourself beforehand (if you're already using e.g. a custom script/Makefile/whatever to specify `--output` then you might as well just add the `rm -Rf`.)

Although the fact that the files are not *overwritten* is an omission.

It should be fixed on `master` now. Thanks for the report!

**Comment by nic-hartley** [comment]
@koute You're welcome! I hadn't considered protecting the user from when they specify the wrong directory. After all, I never make mistakes-- wait, hold on...

Joking aside, I don't really like this solution, though -- there are three use cases I'm thinking about.

- I have one special folder for the `deploy`ed code, and I want it completely clean of anything _except_, well, those deployed artifacts. I want old stuff deleted. (This is my use case.)
- I'm trying to drop my cargo-web stuff into an existing directory, and want everything to be left, with those files overridden.
- I accidentally specified the wrong directory, and am now panicking that I just overwrote `index.html` in another directory.

It sounds like, of those three, only the second is really supported. I think it could be done a bit more cleanly by making the following changes:

- Make `--output` to an existing directory an outright error.
- Add a flag which tells `deploy` to keep the directory, but overwrite the files in it.
- Add a flag which tells `deploy` to entirely delete and reset the directory.

The default would still have its special case (equivalent to defaulting the second flag on instead of off), because frankly, it'd be a pain otherwise. However, now, if someone accidentally specifies `www/` when they meant `www/wasm-demo`, it won't overwrite `index.html` for them unless they _explicitly_ tell it to. In addition, if (like me) you want to clear out old artifacts, it'll do that, too, without needing to add any other commands.

After all, if you're fine with making people add another command, why not remove `--output` entirely? No, really -- it's just a `mv target/deploy /output/location`, plus or minus globs which I don't have the patience to work out right now. It's kind of gross, yes, but so is requiring `rm -rf /output/location` to get the default behavior in a non-default location.

**Comment by koute** [comment]
On one hand you *do* have a point, on the other hand the goal here never was to completely put on the training wheels and not let the user shoot themselves *at all* (after all other command-line tools like e.g. `rm`, `cp`, `gcc`, `tar`, etc. will happily overwrite files if told to do so, so this shouldn't be a surprise). I just wanted to prevent a potential `rm -Rf` thermonuclear explosion.

Perhaps you'd be fine with just adding a flag (`--force-delete-output`?) which would turn on the `rm -Rf` behavior for a custom output directory?

**Comment by nic-hartley** [comment]
@koute I guess I'm just confused about the desired behavior. Is `cargo web deploy` supposed to put the build artifacts into the specified directory? Or is it supposed to make a directory containing just the build artifacts? The two are very similar, but not quite the same. I've been operating under the assumption that it's the latter, because that's how I'm using it (I'm generating my whole site through Cargo, using some extra build scripts), but if it's the former, then I'm just wrong about what cargo-web is meant to do.
