### ISSUE TITLE
Support for --offline

### ISSUE THREAD

**Issue by kellytk** [koute/cargo-web#204]
`cargo web build --release --offline` and `cargo web --offline build --release` output "Found argument '--offline' which wasn't expected, or isn't valid in this context".

`cargo --offline web build --release` outputs "warning: spurious network error (2 tries remaining): curl error: Could not resolve host: github.com" implying `--offline` wasn't honored.

Is `--offline` supported?  If so, how should it be used with `cargo web build`?

**Comment by koute** [comment]
It is currently not supported, but adding it should be fairly trivial as AFAIR it will mostly involve just adding an extra `bool` field to `Build`, `BuildArgs` and `BuildConfig` structs (and fixing the resulting errors), and then just passing `--offline` to cargo in `BuildConfig::as_command` if that boolean was set.

**Comment by kellytk** [comment]
> Build

Where is that struct located?

**Comment by koute** [comment]
> > Build
> 
> Where is that struct located?

```
$ rg "struct Build"
...
src/lib.rs
...
326:struct Build {
...
```

(:

**Comment by kellytk** [comment]
Thanks and pardon me.  I had searched the repo using GitHub's search feature but without quoting the string.

**Comment by koute** [comment]
It's no problem; don't worry about it. (:

**Comment by Pauan** [comment]
@kellytk In my experience GitHub's search feature is very bad: it **very** often misses things, even when you type in the exact correct phrase. So I've learned to never rely upon it.

**Comment by kellytk** [comment]
I've cloned the repo and it's generating 11 errors.  Does an always-good branch that I can develop against exist?

**Comment by kellytk** [comment]
I've cloned the repo and it's generating 11 errors. Does an always-good branch that I can develop with exist?

**Comment by kellytk** [comment]
My only use of `cargo web`, `Yew`, has removed it as a requirement.
