### ISSUE TITLE
deploy performance different from build --release

### ISSUE THREAD

**Issue by benkonz** [koute/cargo-web#223]
I've noticed that my project runs __much__ faster when I copy over the .wasm file from running `cargo-web build --release` compared to when I build my just deploy my project normally with `cargo-web deploy`. Why is this the case? I was under the impression that `deploy` did a release build

**Comment by Pauan** [comment]
`cargo web deploy` only builds the project and puts it into the `target/deploy` folder.

If you want to build in release mode you need to use `cargo web deploy --release`.

**Comment by benkonz** [comment]
I see, thanks!
