### ISSUE TITLE
cargo install fails in nightly

### ISSUE THREAD

**Issue by spease** [koute/cargo-web#25]
Technically this has its root cause in another crate, but may require upgrading another package version to get the fix.

I get
```
error[E0583]: file not found for module `montgomery`
```

in ring v0.11.0 when trying to install with rustup override set to nightly for the directory. It looks like this is fixed at least in ring 0.13.0:
https://github.com/briansmith/ring/issues/598

If I install with stable, it runs fine.

**Comment by koute** [comment]
Yeah, it will most likely require an update of a whole bunch of crates due to `hyper` going async... \*sigh\*

**Comment by jsonnull** [comment]
Is there a workaround for this in the meantime?

**Comment by krircc** [comment]
```rust
rustup default nightly-2017-12-20
```
it's work

**Comment by koute** [comment]
Yep, just as @krircc said, for now you can use an older nightly, or compile on stable.

**Comment by gmorenz** [comment]
If you only want to use the older version of rust for a certain project run

    rustup override set nightly-2017-12-20

in the correct directory.

**Comment by koute** [comment]
Fixed on `master`. I'll release a new version on `crates.io` Soon™.
