### ISSUE TITLE
Why does cargo-web download emscripten and binaryen even though I have them installed?

### ISSUE THREAD

**Issue by svenstaro** [koute/cargo-web#27]
Basically see title. I'm using Arch Linux and have emscripten and binaryen installed and working using provided packages but cargo-web still tries to download these. Can't it use system packages?

**Comment by koute** [comment]
It can, if you pass it the `--use-system-emscripten` flag. By default it always downloads Emscripten for consistency's sake across multiple distributions.

I would definitely be willing to add a feature flag which would flip this default to be the other way around.

**Comment by svenstaro** [comment]
Thank you, I didn't see that flag!
