### ISSUE TITLE
Import math functions (sin, cos, etc.)

### ISSUE THREAD

**Issue by samnardoni** [koute/cargo-web#28]
Currently, using some math functions e.g. `(1.0 as f64).sin()` with wasm results in a runtime error.

I'm not sure whose "fault" it is, nor where the best place to solve it is; but, one way is to provide these functions in the `import` section when instantiating the wasm module. 

```javascript
env: {
  // ...
  "sin": Math.sin
  "cos": Math.cos
  // ...
}
```

I'm not that familiar with wasm-JS interop, so this could be horribly inefficient. But, is _slow_ worse than _broken_?

**Comment by koute** [comment]
Ah yes, this slipped my mind.

Yes, I do plan on automatically detect when such imports are necessary and generate them for you.

**Comment by koute** [comment]
Fixed. If you find any other functions which I've omitted (I'm sure there are some) then please create a new issue.

**Comment by samnardoni** [comment]
That was fast! Fantastic. Thanks.
