### ISSUE TITLE
Add ability to generate default static content

### ISSUE THREAD

**Issue by ndarilek** [koute/cargo-web#30]
It would be helpful to add a subcommand that generates default static content at the correct path. I'd like to modify the default HTML, but am not immediately sure what it should look like. I suppose I could wget the result of `cargo web start`, but I don't know what parts of that are needed in the static directory and what aren't.

Further, I thought `cargo web build` would output everything I'd need to host a wasm app on a static site, but I can't find any HTML to post. Maybe I'm fundamentally misunderstanding something about how to host an app?

Thanks.

**Comment by koute** [comment]
You can check out the default HTML in `src/cmd_start.rs`. As you can see it's very simple. The canvas thingy is for Emscripten so that libraries like SDL can work. Besides that there are no requirements from the HTML side - you can just add a `<script>` to your HTML to include the JS and it will work.

I agree that this should be better documented, and I guess we should probably have a command which would output the artifacts so that the user doesn't have to hunt them down manually in `target`.

**Comment by ndarilek** [comment]
Thanks, for the moment I just curl'd the HTML. I see a canvas is 
automatically created. If I know in advance that I need the canvas, can 
I create and style it myself? If so, does it need a specific ID, or does 
Emscripten just grab whatever canvas it finds?

**Comment by ndarilek** [comment]
Ah, I see, I have to set __cargo_web.canvas to the canvas I want to use?

**Comment by koute** [comment]
Emscripten looks for the handle to the canvas in `Module.canvas` (where `Module` is a global object), so whatever you'll put in there will be used by Emscripten, regardless of how it's styled or what ID it has.

Also, AFAIK the canvas is actually optional, so if you don't need it then you don't need it. (If you're not, for example, using libraries like SDL then you most certainly don't need it.)

**Comment by ndarilek** [comment]
Another confusion about the static content, and I don't know if this should go here or in a new issue:

If I run `cargo web build`, my expectation is that I'd get a directory ready to upload to my web server. This means:
 * Contents of static/ are placed alongside the build artifacts.
 * References in the HTML are correct (I.e. /js/app.js should reflect the actual built loader, which at the moment seems to be named <appname>.js.)

That doesn't seem to be the case, though. src/static only seems to benefit the `cargo web start` task. But if you do any sort of complex worlflow, you're going to have to munge the static HTML to at least replace paths and artifact names.

Am I missing something obvious?

In any case, thanks for all your work on this. You've made the webasm/emscripten build process amazingly easy and accessible, and I'm having a hell of a great time building on this platform.

**Comment by koute** [comment]
That is a very reasonable expectation, however the `build` command itself might not be the best place to put such functionality - the `target` directory has *a lot* of gunk that we don't need nor care about.

That said, I very much agree that we should have a subcommand which would gather everything for you ready to be uploaded on your web server. In fact, we have an issue for that already: #1

**Comment by koute** [comment]
FYI, I've just pushed an initial version of what you've requested to `master` in the form of `cargo web deploy` subcommand.

**Comment by koute** [comment]
Just published a new version which has this added, so closing!
