### ISSUE TITLE
Broken source maps?

### ISSUE THREAD

**Issue by wldcordeiro** [koute/cargo-web#32]
This is something I'm not sure where the problem lies in as I found it via testing [yew](https://github.com/DenisKolodin/yew) but it appears that while a source map is generated, neither Chrome or Firefox can find it. Maybe this isn't a problem with cargo-web and might be a misconfiguration of yew. I'm building with the emscripten target and not the built-in WASM from Nightly currently (using stable Rust from Rustup)

<img width="1241" alt="screen shot 2018-01-03 at 9 33 07 am" src="https://user-images.githubusercontent.com/580982/34529441-346269e4-f069-11e7-9968-34f01e8f52d5.png">
<img width="1523" alt="screen shot 2018-01-03 at 9 33 30 am" src="https://user-images.githubusercontent.com/580982/34529442-34856502-f069-11e7-81f9-95ecc2685fa1.png">

**Comment by koute** [comment]
Ah, right, I didn't realize Emscripten actually generated source maps in the `deps` directory.

I'll add support for them once I'll refactor the current way of finding artifacts (since as-is it's too brittle to support anything more complex).

**Comment by wldcordeiro** [comment]
Thanks @koute I'd love to help out with this kind of work. I'm super interested in WASM, Rust and getting away from writing JS. 😈

**Comment by koute** [comment]
@wldcordeiro Well then you're in luck as there is plenty of work to do. (:

*If* you would ever be interested in helping out with either `stdweb` or `cargo-web` and don't know where to start I'm always willing to mentor you through it.

**Comment by wldcordeiro** [comment]
Thanks @koute I'm in the mozilla IRC and I'd love some help getting familiar with Rust by diving into projects. 😄 I haven't had a ton of opportunities to work on Rust stuff that I could understand well, Servo was daunting! These seems much easier to get into and thanks to them interoping with JS I'm working in a domain I'm very familiar with.

**Comment by wldcordeiro** [comment]
Also I'm really interested in things like source maps as I'm a maintainer for the Firefox debugger and we totally want to get a great debugging story in place for Rust!

**Comment by koute** [comment]
@wldcordeiro As far as source maps are concerned AFAIK they *should* work properly with the Emscripten backend as far as I know provided we'll fix this tiny issue of `cargo-web` ignoring them currently (but that has to wait until I'll finish my current refactoring of `cargo-web`'s interface with `cargo`, which will also fix some other issues.). With the native Rust WASM backend I *think* it's still too early to think about that, as it requires support from the compiler.

Considering your experience with Firefox, *if* you're interested. (If not then that's perfectly fine!) one of the issues I'd love to get some help with is this one https://github.com/koute/cargo-web/issues/33 even if it's just going to be stuff like research.

**Comment by wldcordeiro** [comment]
@koute native Rust WASM is supported in Firefox debugger but I believe we have it behind a preference (see this little demo: https://twitter.com/slsoftworks/status/941400137921949696) 

I wouldn't know a ton for the headless mode, I know Firefox recently added the full support of it a release or two back so I imagine it'd be starting a Firefox process with the right arguments for ports and whatnot?

**Comment by koute** [comment]
> @koute native Rust WASM is supported in Firefox debugger but I believe we have it behind a preference (see this little demo: https://twitter.com/slsoftworks/status/941400137921949696)

I've seen this but someone in that Twitter thread wrote:

> afaict you just just emscripten (not the direct rustc wasm backend) and it just works.

**Comment by Zydnar** [comment]
I know it's quite old issue, but it would be nice to have simple switch to generate source maps. Here is how it's done: [https://github.com/yurydelendik/old-man-sandbox/tree/master/rust-wasm-hey](https://github.com/yurydelendik/old-man-sandbox/tree/master/rust-wasm-hey)
The idea is to run `rustc` with `-O -g` parameters and then run `esmsdk/upstream/tools/wasm-sourcemap.py` with parameters ` ./nested_list.wasm -o ./nested_list.wasm.map --dwarfdump C:\Users\User\Documents\emsdk\upstream\bin\llvm-dwarfdump.exe`. So when cargo web build is being run it actually runs rustc, all we need is adding -O and -g parameters to rustc and after all running python script. Tested on yew framework example build with cargo-web. Unless we run cargo web with --release switch it could be default behavior. sourcemap.py has also ability to strip wasm from debug info.

**Comment by Zydnar** [comment]
I know it's an old issue but it would be nice to have an easy way to generate source-maps, there is working solution: [https://github.com/yurydelendik/old-man-sandbox/tree/master/rust-wasm-hey](https://github.com/yurydelendik/old-man-sandbox/tree/master/rust-wasm-hey) the idea is to run `rustc` with `-O -g` parameters and then `emsdk\upstream\emscripten\tools\wasm-sourcemap.py` with `your.wasm -o your.wasm.map --dwarfdump emsdk\upstream\bin\llvm-dwarfdump.exe` . Maps load and I can see sources but still I make something wrong and I get `Uncaught (in promise) TypeError: Cannot perform Construct on a detached ArrayBuffer`, so wasm file can't load Maybe it's something wrong in generated JS file...?
