### ISSUE TITLE
JSON output on stdout

### ISSUE THREAD

**Issue by dflemstr** [koute/cargo-web#34]
When using `cargo web` in a script or from a different tool it would be great to get log output as line separated JSON objects so that they can be parsed into meaningful data to be displayed to the user.

Normal cargo already supports this so I guess it's only a question of passing through a flag and maybe logging additional things from this tool (such as the location of generated js files)

I want to add support for richer error handling in https://github.com/dflemstr/rust-native-wasm-loader and lacking support for this makes things harder than necessary.

**Comment by koute** [comment]
> Normal cargo already supports this so I guess it's only a question of passing through a flag and maybe logging additional things from this tool (such as the location of generated js files)

Unfortunately it's not only a question of passing through a flag, however coincidentally I'm currently in the process of rewriting how I launch `cargo` and interact with it, so after I'm finished I'll be able to easily support this.

**Comment by koute** [comment]
@dflemstr I've just added support for `--message-format=json` on `master`. The format is exactly the same as the one `cargo` emits.

**Comment by dflemstr** [comment]
Finally had time to try this out. Seems to do exactly what I need, great!
