### ISSUE TITLE
Customize code for loading wasm file

### ISSUE THREAD

**Issue by dflemstr** [koute/cargo-web#35]
When using this tool combined with common web infrastructure such as webpack, it's useful to be able to control how the wasm file is loaded from Javascript instead of hardcoding a fetch call.

It might be useful to use the native wasm support in Webpack 4 for example, where the exports from a wasm file can be imported simply using `import {myfunction} from "bla.wasm";`

We might also want to put the wasm file on a CDN or integrate it with a service worker asset loader etc. which also requires being able to customize the wasm file url.

Right now I do this by search replacing the generated url like so: https://github.com/dflemstr/rust-native-wasm-loader/blob/f30905197637b7e3dbccfdd1ac61a43709d395d5/index.js#L68

**Comment by koute** [comment]
Related: https://github.com/koute/cargo-web/issues/24

> When using this tool combined with common web infrastructure such as webpack, it's useful to be able to control how the wasm file is loaded from Javascript instead of hardcoding a fetch call.

Yes this is something I definitely want to support. How much control is necessary here? Only change the filename? Call another arbitrary function which will do the loading?

> It might be useful to use the native wasm support in Webpack 4 for example, where the exports from a wasm file can be imported simply using `import {myfunction} from "bla.wasm";`

The unfortunate thing about WASM is that currently it support an extremely limited set of types, so I'm guessing the usefulness of that might be somewhat limited? (Although I wouldn't mind supporting that, though if Webpack directly loads the WASM file is there anything that would have to be done to support it?)

Anyhow, if you take a look at the "Exposing Rust functions to JavaScript" section in [stdweb](https://github.com/koute/stdweb) you'll see an alternative way to export functions from Rust to JavaScript, and exporting functions like that supports **a lot** more types (strings, vectors, JS references, typed arrays, DOM elements, etc.).

I'd love to support that with Webpack so that you could do an `import` just like you've shown and be able to import one of the functions exported the `stdweb`-way. Do you know if/how feasible that would be?

**Comment by dflemstr** [comment]
Apologies for a somewhat low-quality issue description, I was using my phone and now I have a full keyboard again.

What I was referring to in this issue was mostly what the `cargo-web` generated Javascript looks.  I agree that using the webpack built-in support for loading wasm doesn't aid in usability.  What it does is help with mapping and minifying assets in a consistent way.

Imagine if the `cargo-web` generated Javascript (`my_rust_crate.js`) looked somewhat like this:

```js
import {my_rust_function} from "my_rust_crate.wasm";

// JS version of my_rust_function (using convention snake_case => camelCase for example)
const myRustFunction = (foo) => {
  // ... do necessary bridging from JS to wasm
  const result = my_rust_function(fooBridged);
  // ... do necessary bridging from wasm to JS
  return bridgedResult
}

export myRustFunction;
```

The benefit is that webpack figures out the async loading of the `wasm` file so you don't have to riddle your code with promise calls everywhere; you can use the functions as if they were synchronous.  You can also define webpack bundling rules to put all wasm files at `/public/wasm/[name].[hash:8].wasm` for example without having to have `cargo-web` know about it; webpack will update all imports automatically.

I suppose we can close this as a duplicate of #24 if you think that they are similar enough?

**Comment by koute** [comment]
So, basically, generate a different runtime for webpack?

Question - can you also dynamically do the `export myRustFunction` or simply give it an object with functions and make it export everything from that object? (Please forgive me for perhaps silly questions, but my experience with webpack is unfortunately very limited.)

> I suppose we can close this as a duplicate of #24 if you think that they are similar enough?

Nah it's fine.

**Comment by dflemstr** [comment]
> Question - can you also dynamically do the export myRustFunction or simply give it an object with functions and make it export everything from that object? (Please forgive me for perhaps asking a silly question, but my experience with webpack is unfortunately very limited.)

Well, you can export an object and modify that object later of course (it's just vanilla Javascript).  Then minification will of course not know about the contents of that object which means that those functions can't be renamed/inlined/etc.

As a separate feature request it would be great to be able to export functions in `stdweb` declaratively for that reason ;)

**Comment by koute** [comment]
> As a separate feature request it would be great to be able to export functions in stdweb declaratively for that reason ;) Maybe worth creating an issue for that?

Yep, that is indeed actually a great idea, and it will also allow me to trivially generate a runtime which would mesh well with webpack.

No need for an issue; I'm already working on it. (:

**Comment by koute** [comment]
@dflemstr FYI, I've added **experimental** support for this in the newest `cargo-web`. If you pass `--runtime=experimental-only-loader` when building a non-standalone runtime will be generated which doesn't fetch the WASM module by itself. I used it in my [Parcel plugin](https://github.com/koute/parcel-plugin-cargo-web) if you'd like to take a peek on how it's supposed to be used.

**Comment by dflemstr** [comment]
@koute I tried using this from my loader now.  Basically, my generated code boils down to:

```js
// Generated by rust-native-wasm-loader
var loadWasm = require("...path to cargo-web generated wasmFile...");
// ... contents of cargo-web generated js file ...
module.exports = loadWasm().then(function (result) {
  return __initialize(result.module);
});
```

However this turns out to be problematic.  The `loadWasm` function that I get from e.g. `wasm-loader` actually tries to instantiate an instance of the wasm module.  However the code generated by `cargo-web` assumes that *it* is responsible for instantiating the module and calls `WebAssembly.instantiate` directly ([like this](https://github.com/ballercat/wasm-loader/blob/master/output.js#L10-L18)).  The code above fails because I call `loadWasm()` without any arguments, which loads the module with the wrong imports and fails.

I would be very happy if `cargo-web` simply produced an imports object for me (currently `__imports` in the generated code) and exposed `__instantiate`, that would additionally return `Module.exports`, and I could control everything else myself.  Then I could do something like:

```js
// Generated by rust-native-wasm-loader
var loadWasm = require("...path to cargo-web generated wasmFile...");
// ... contents of cargo-web generated js file ...
module.exports = loadWasm(__imports).then(function (result) {
  return __instantiate(result);
});
```

**Comment by koute** [comment]
@dflemstr I'll try to whip something like that up in the next version of `cargo-web`.

**Comment by koute** [comment]
Long supported with the `--runtime library-es6` option; closing.
