### ISSUE TITLE
Consider making ALLOW_MEMORY_GROWTH=1 the default

### ISSUE THREAD

**Issue by Pauan** [koute/cargo-web#40]
I tried compiling my Rust application with `--target-webasm-emscripten` but when I ran it, I got this runtime error:

```
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher
than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows
increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY
to a higher value before the program runs, or (4) if you want malloc to return NULL (0)
instead of this abort, compile with  -s ABORTING_MALLOC=0 
```

According to the Emscripten docs, you can use [ALLOW_MEMORY_GROWTH](https://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-Code.html#memory-growth) to fix this.

I recommend adding `-s ALLOW_MEMORY_GROWTH=1` by default to the `emcc` command, since it has little to no downside on WebAssembly.

**Comment by koute** [comment]
Thanks for the great suggestion!

Done on `master`.
