### ISSUE TITLE
Conditional compilation

### ISSUE THREAD

**Issue by Pauan** [koute/cargo-web#41]
When compiling my Rust application with `--target-asmjs-emscripten` I ran into some situations where there are APIs which are simply not supported in JS (such as threads), which then causes a runtime panic.

I would like to be able to compile my application for use on either the desktop (with full support) or JS / Wasm (without support for things like threads) and conditional compilation seems like a good way to accomplish that.

However, I wasn't able to find a way to do that. The `--features` flag doesn't work, and I couldn't find whether `cargo-web` sets a special config flag when compiling. Is conditional compilation supported, or planned to be supported?

P.S. I'm a JavaScript expert, learning Rust, and I would really like to be able to use Rust on the web, so I'm interested in helping out with pull requests.

**Comment by koute** [comment]
You can do that already pretty easily, unless I misunderstood something.

A few examples so that you can see how it works:

```rust
#[cfg(all(target_arch = "wasm32", target_os = "unknown"))]
fn foobar() {
    // Will be defined only on Rust's native WASM backend.
}

#[cfg(target_arch = "wasm32")]
fn foobar() {
    // Will be defined only when compiling to WASM, either using Rust's native backend or Emscripten.
}

#[cfg(any(target_arch = "wasm32", target_arch = "asmjs"))]
fn foobar() {
    // Will be defined only when compiling to WASM or asmjs, on either of Rust's backends.
}

#[cfg(not(any(target_arch = "wasm32", target_arch = "asmjs")))]
fn foobar() {
    // Will be defined only when NOT compiling to either WASM or asmjs.
}
```

Will this work for you?

**Comment by Pauan** [comment]
@koute Yes, that's exactly what I was looking for, thanks!

I didn't realize that the `wasm32` arch would work.
