### ISSUE TITLE
Terminal colors are broken on Windows

### ISSUE THREAD

**Issue by coder543** [koute/cargo-web#43]
With the latest release of `cargo-web`, the output on PowerShell looks like this:

![image](https://user-images.githubusercontent.com/726063/34804064-a864fd4e-f644-11e7-867b-8327d724ce99.png)

I don't remember this being an issue with the 0.4.x series, but I can't remember if I actually tested the 0.4.x series on my Windows computer, or if I had merely installed it here. I know I had played with `cargo web` on my Linux laptop. Either way, the colors seem to be broken now.

**Comment by koute** [comment]
Does this happen only for the `Compiling xxx vx.x.x` messages (which are printed out by `cargo`) or to error messages too (which are printed out by `cargo-web`)? For example, if you try to compile this on Windows:

```rust
fn main() {
    xxx
}
```

**Comment by coder543** [comment]
Testing that code with `cargo web start --target-webasm --release`

![screenshot_2018-01-11_11-13-34](https://user-images.githubusercontent.com/726063/34834627-8016dfca-f6c0-11e7-9536-beae4c759b03.png)

For comparison, when I do `cargo build` in the same project, I get this:

![screenshot_2018-01-11_11-14-32](https://user-images.githubusercontent.com/726063/34834702-a017b4f2-f6c0-11e7-98a7-39ba87cc2b4e.png)

I took the screenshots through a remote desktop tool, since I'm not at my Windows computer right now, so they might be a little grainy.

Cargo's colors work just fine, since Windows is a first-class platform in the Rust toolchain. Something is happening inside `cargo-web`, but I'm not sure where or what.

**Comment by koute** [comment]
Yeah, unfortunately `cargo-web` must catch all of `cargo`'s output and regenerate it itself.

For now I've disabled colors on Windows altogether since right now I don't have a Windows machine on hand to fix it.

**Comment by koute** [comment]
Just published a new version which has this fixed, so closing! (For now the colors are disabled; I'll reenable them some day when I'll have the change to do some testing under Windows.)
