### ISSUE TITLE
Allow custom html files for cargo web start

### ISSUE THREAD

**Issue by svenstaro** [koute/cargo-web#44]
I'd like to use my own custom `index.html` when starting the cargo web server.

**Comment by koute** [comment]
I think this should work already; does it not? Just put a `static` directory in the root of your crate and put an `index.html` in there.

**Comment by svenstaro** [comment]
Oh, alright then. Works for me. I think this is a common use case and should perhaps be documented.

**Comment by koute** [comment]
Yep. I'm going to try to improve the documentation soon after I finish what I'm working on now.

**Comment by koute** [comment]
Docs updated; closing!
