### ISSUE TITLE
How to build this with -s ASYNCIFY=1?

### ISSUE THREAD

**Issue by svenstaro** [koute/cargo-web#45]
So I know I can use Web.toml to define `link-args = ["-s", "ASYNCIFY=1"]` but that's not the issue here. I get this with either `link-args = ["-s", "ASYNCIFY=1"]` in Web.toml or `EMMAKEN_CFLAGS="-s ASYNCIFY=1" cargo web build --target-wasm-emscripten --use-system-emscripten --release`:
[log.txt](https://github.com/koute/cargo-web/files/1624750/log.txt)

Without that line or env var it works fine. However! `EMMAKEN_CFLAGS="-s ASYNCIFY=1" cargo build --target wasm32-unknown-emscripten --release` works just fine and has the desired effect. What's up here?

**Comment by koute** [comment]
Hmmm....

With the automatically installed Emscripten (1.37.27) the compilation also fails on my machine (but with an entirely different error than yours), however if I use older Emscripten which I have installed system-wide (1.37.25) it works (`cargo-web build --target-webasm-emscripten --release --use-system-emscripten` with the asyncify flag added to `Web.toml`).

Which version of Emscripten are you currently using? Can you also try to do this before building?

```
rm -Rf ~/.emscripten ~/.emscripten_cache ~/.emscripten_cache.lock ~/.emscripten_sanity
```

**Comment by svenstaro** [comment]
It fails for me with 1.37.25 even after deleting those dirs. I'll compile 1.37.28 and try again (and in fact I'll bump the version of Emscripten in Arch as well).

**Comment by svenstaro** [comment]
I just tried with emscripten 1.37.28 and that fails with a similar error even after deleting the dirs you mentioned as well as `target`: 
[log2.txt](https://github.com/koute/cargo-web/files/1626944/log2.txt)

I even updated my binaryen to 41.

**Comment by koute** [comment]
Hmm...

A few other things you could try:

1) update your Rust,
2) if it works standalone without `cargo-web` then you could set `CARGO_WEB_LOG=cargo_web=debug`, try to build your project, and then based on what the debug logs tell you (it will print out the RUSTFLAGS and cargo arguments it used when building) try to launch it manually with exactly the same parameters and try to successively reduce it down so we could figure out why exactly it fails.

**Comment by svenstaro** [comment]
It does appear to be related to enabling lto. Can you try that and report your results?

**Comment by svenstaro** [comment]
Turns out ASYNCIFY should not be used anymore and instead [Emterpreter](https://github.com/kripken/emscripten/wiki/Emterpreter) should be used.
