### ISSUE TITLE
`check_if_command_exists` broken on windows

### ISSUE THREAD

**Issue by Diggsey** [koute/cargo-web#47]
`chrome.exe --version` does not print out version information on windows, it just launches a new window. You can use `which`/`where` to check whether a command exists without running it - there's an implementation in rustup you can steal.

**Comment by koute** [comment]
> there's an implementation in rustup you can steal

Could you perhaps link to it?

**Comment by Diggsey** [comment]
```rust
pub fn has_cmd(cmd: &str) -> bool {
    let cmd = format!("{}{}", cmd, env::consts::EXE_SUFFIX);
    let path = env::var_os("PATH").unwrap_or(OsString::new());
    env::split_paths(&path).map(|p| {
        p.join(&cmd)
    }).any(|p| {
        p.exists()
    })
}

pub fn find_cmd<'a>(cmds: &[&'a str]) -> Option<&'a str> {
    cmds.into_iter().map(|&s| s).filter(|&s| has_cmd(s)).next()
}
```

**Comment by koute** [comment]
Thanks! Should be fixed on `master`.

**Comment by koute** [comment]
Just published a new version which has this fixed, so closing.
