### ISSUE TITLE
Conditional Platform-specific dependencies not working in Cargo.toml in Windows

### ISSUE THREAD

**Issue by edwin0cheng** [koute/cargo-web#50]
My Cargo.toml contains these lines:

```
[target.'cfg(target_arch = "wasm32")'.dependencies]
stdweb = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
glutin = "*"
```
But when i use cargo web build --target-webasm to build, it still be referenced glutin.
Did i do something wrong ? Or how can switch between normal arch and wasm32 one ?

**Comment by koute** [comment]
Hmm... it works here on Linux as you'd expect.

In general `cargo-web` itself has nothing to do with dependencies you declare in your `Cargo.toml`, so *if* it really always tries to build `glutin` regardless of the target as you say then it's most likely a `cargo` bug.

Can you try this and see if it tries to build `glutin`? `cargo build --target=wasm32-unknown-unknown`

**Comment by edwin0cheng** [comment]
Just tried, it build successfully (it didnt build glutin.)

However, if i build with "cargo web build --target-webasm", the actual errors are :

```
D:\sandbox\rust-tests\webgl-rs\example>cargo web build --target-webasm
thread 'main' panicked at 'Unknown target kind: 'rlib'', src\cargo_shim\mod.rs:95:38
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: BaseThreadInitThunk

```

So i was guessing it was building glutin, but i am not so sure.

**Comment by koute** [comment]
This should now be fixed on `master`. Could you try it out and tell me if it works for you?

**Comment by edwin0cheng** [comment]
Just cloned,  and tested master in my windows, it works now. Thank you so much.
