### ISSUE TITLE
`start` not rebuilding code on change

### ISSUE THREAD

**Issue by ndarilek** [koute/cargo-web#54]
Seems like this used to work, but it no longer does, and the `-v` option doesn't provide any clarity. Running the V0.6.0 release under Linux.

Thanks!

**Comment by ndarilek** [comment]
Did some digging. This, too, is related to the fact that I'm building a library crate. Cargo-web indicates that `&last_build.target.source_directory` is $crate_root/src/bin, not $crate_root/src.

I can probably refactor this crate from lib to bin I built it initially not knowing whether I could build all my native dependencies in Emscripten, so thinking I might need JNI. Still, though, might be good to fix this. I don't know if there's a struct member that points at $crate_root/src, but that's probably a better candidate for watching.

Thanks.

**Comment by koute** [comment]
Wait... how did you do that? The `start` command explicitly looks for a `bin` crate and refuses to start when it doesn't find one.

**Comment by ndarilek** [comment]
Maybe I'm misunderstanding what bin/lib crates are.

My crate had src/lib.rs containing the main code, re-exports of other 
modules, etc. It also had src/bin/mycratename.rs built as a binary using 
my lib. My initial intent was to test functionality as I built it using 
this binary, then eventually wrap src/lib.rs via swig and use it on 
Android. Yesterday I made src/bin/mycratename.rs get its main function 
from either src/shell.rs or src/web.rs depending on whether it built on 
Emscripten or not. This worked, in that it compiled and ran, but it 
failed to detect changes with `start`, and as discussed elsewhere, 
static file handling behaved in a surprising way.

So maybe the edge case here is that detection doesn't work when a lib 
crate contains a binary.

In any case, since it's pretty clear that I can move ahead with wasm 
(barring my native libraries failing at the point when I actually start 
using them) I switched to src/main.rs containing both src/lib.rs and 
src/bin/mycratename.rs. I assume that's now a bin crate, and that seems 
to work just fine.

**Comment by koute** [comment]
Ah yes, now I understand the problem! What you have is a hybrid `lib`/`bin` crate, and it only monitors the `bin` part while the `lib` part is implicitly used.

I'll fix it.

**Comment by koute** [comment]
This should be fixed now on `master`. As a bonus I've added tracking of dependencies and support for modifying `Cargo.toml`.

Can you try it out and tell me if it works for you?

**Comment by ndarilek** [comment]
Ack, already switched to a bin crate, but over the next day or so I'll 
check out an older version and test this out.

Thanks!

**Comment by koute** [comment]
I think this should be fixed now, so closing! If you'll have any further problems feel free to create a new issue.
