### ISSUE TITLE
Trailing zeroes in static files

### ISSUE THREAD

**Issue by DenisKolodin** [koute/cargo-web#70]
Hi!
I'm moving to `stdweb` 0.4.0. It's a good thing! Thank you!
But I've found a strange behavior in `cargo-web`.
It adds extra zeroes to `*.json` file and I striked to `Err(ErrorImpl { code: TrailingCharacters, line: 4, column: 1 })` of `serde` with https://github.com/DenisKolodin/yew/tree/master/examples/dashboard/client example.

Look at the sizes.

**Original:**
```
denis@localhost ~/yew/examples/dashboard/client (stdweb-0.4.0) $ ls -la static/data.json 
-rw-rw-r--. 1 denis denis -   21 bytes   - Dec 31 00:41 static/data.json
```

**Returned from server:**
```
denis@localhost ~/yew/examples/dashboard/client (stdweb-0.4.0) $ ls -la ~/Downloads/data.json 
-rw-rw-r--. 1 denis denis -   4096 bytes   - Feb 22 22:14 /home/denis/Downloads/data.json
```

Returned file contains:
```
00000000: 7b0a 2020 2020 2276 616c 7565 223a 2031  {.    "value": 1
00000010: 3233 0a7d 0a00 0000 0000 0000 0000 0000  23.}............
00000020: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000030: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000040: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

But the original contains this only:
```
00000000: 7b0a 2020 2020 2276 616c 7565 223a 2031  {.    "value": 1
00000010: 3233 0a7d 0a                             23.}.
```

@koute, What do you think about it?

UPD: cargo-web 0.6.8 (updated today from https://github.com/koute/cargo-web/commit/175a9f123db0e5327bc784c1d0c8a61e24433a0f state)

**Comment by koute** [comment]
Thank you for the report!

Yes, this is a bug in `cargo-web` introduced when we replaced `rouille` with pure `hyper`. The version of `cargo-web` currently on `crates.io` works fine.

Since we don't have tests yet for `cargo web start` the bug slipped under my radar. I always test this functionality manually before releasing, and I haven't yet got to the point of releasing new `cargo-web`.

Anyhow, I think this is a great opportunity for me to finally add some tests to avoid such situations in the future!

**Comment by koute** [comment]
Fixed on `master`!

**Comment by DenisKolodin** [comment]
I've checked it now - works perfect! Thank you!
