### ISSUE TITLE
Are there any plans to allow use as a library?

### ISSUE THREAD

**Issue by daboross** [koute/cargo-web#74]
I'm currently building a cargo subcommand for deploying Rust WASM apps to a specific domain, and I'm currently calling `cargo-web` manually via `std::process::Command`. I'm wondering if there is any possibility in the future of inlining the functionality, so someone installing the binary I'm building wouldn't have to install `cargo-web` separately.

It'd be nice even if the interface was a single public function `run(args: &[OsString])`. Of course, more granularity / manual control would be appreciated, but anything allowing it to be included as the same binary at all would be nice.

Not a high-priority concern at the moment, I'm mostly wondering if there are any existing plans. Thanks!

**Comment by koute** [comment]
Well, I haven't been planning anything like that, but I certainly wouldn't be against it per-se if someone needed it!

**Comment by daboross** [comment]
Cool! I can work on a PR to submit which would involve moving main.rs into lib.rs and then creating a shim main.rs which just calls into the library, if that sounds alright.

My use case is for a hobby project and thus not too important, but I could imagine it being useful to anyone wanting to bundle and/or deploy `cargo web` generated binaries in a domain too specific to include in `cargo web` itself.

**Comment by g-s-k** [comment]
+1 on this idea - i'll take a look at implementing it. i want to build my front-end in a build script for my back-end, then embed the files in the binary. it would be cool to be able to use `cargo install` for a full stack application, rather than needing a makefile or dockerfile to orchestrate the steps.

**Comment by ASalvail** [comment]
@koute this should be fixed by #172 ?

**Comment by koute** [comment]
Yep.

**Comment by daboross** [comment]
Thanks @g-s-k!
