### ISSUE TITLE
Cannot use f64::round function

### ISSUE THREAD

**Issue by Pauan** [koute/cargo-web#75]
I'm not sure whether to report this on cargo-web or stdweb, but in any case, here is a reproducible test-case:

```rust
#[macro_use]
extern crate stdweb;

use stdweb::unstable::TryInto;

fn main() {
    let f: f64 = js!( return 10; ).try_into().unwrap();

    js! { @(no_return)
    	console.log(@{f.round()});
    }
}
```

Compile the above code with the `wasm32-unknown-unknown` target and then try running it. I get this runtime error:

```
Error loading Rust wasm module 'example': LinkError: WebAssembly Instantiation: Import #1 module="env" function="round" error: function import requires a callable
    at <anonymous>
```

I inspected the wasm, it looks like this:

https://gist.github.com/Pauan/a6c66b1c5c0a9722953dac98f41d130d

As you can see, the `.wasm` is importing a `round` function, but the `.js` file doesn't provide a `round` function. This might affect the other numeric operators as well.

Operating system: Windows 10 64-bit
rustc version: `1.26.0-nightly (9cb18a92a 2018-03-02)`
cargo-web version: `0.6.8`

**Comment by koute** [comment]
Fixed.

**Comment by Pauan** [comment]
@koute Thanks!
