### ISSUE TITLE
Support virtual manifests

### ISSUE THREAD

**Issue by kuviman** [koute/cargo-web#82]
If cargo workspace's manifest is a virtual manifest, running `cargo web build --package somepkg` is impossible:

    thread 'main' panicked at 'cannot figure out which package is the default'

**Comment by koute** [comment]
Can you put up a minimal example which reproduces the issue?

**Comment by kuviman** [comment]
Sure: https://github.com/kuviman/virtual-manifest-test

**Comment by LaylConway** [comment]
Running into the same issue, this is important for users of atom-ide-rust where the only option is to have a virtual manifest if you want a project with more than one crate.

**Comment by koute** [comment]
This should be fixed on `master`; please take it for a spin and tell me if it works out for you.

**Comment by kuviman** [comment]
Works for me, thanks!

One thing though - `cargo web deploy --package somepkg` deploys to `somepkg/target/deploy`, but should probably be instead somewhere inside in workspace root's `target`, where everything else is.

**Comment by koute** [comment]
Hmm... I suppose you're right!

Should be fixed on `master`.

**Comment by kuviman** [comment]
Thanks
