### ISSUE TITLE
Support node.js VMs

### ISSUE THREAD

**Issue by LaylConway** [koute/cargo-web#85]
This is admittedly a hyper-specific use-case. I'm using cargo-web to make a bot for the game Screeps, which uses node.js VMs to run user code. It currently has two modes user code can be running in:

- Shared, which uses https://nodejs.org/api/vm.html
- Isolated, which will soon become the default and uses https://github.com/laverdet/isolated-vm

In both of these situations, the generated .js file will incorrect use `fetch` (and fail). Even if it did still detect node, it would try to use `fs` which does not work in this environment. In Screeps specifically the WASM file has to be `require`d.

Currently my workaround is to run this powershell file after every build:
```ps1
$js = Get-Content target\wasm32-unknown-unknown\release\mycrate.js
$js = $js.replace('typeof window === "undefined" && typeof process === "object"', 'true')
$js = $js.replace('const fs = require( "fs" );', '')
$js = $js.replace('const path = require( "path" );', '')
$js = $js.replace('const wasm_path = path.join( __dirname, "sair.wasm" );', '')
$js = $js.replace('const buffer = fs.readFileSync( wasm_path );', 'const buffer = require("mycrate")')
$js = $js.replace('typeof window === "undefined" && typeof process === "object"', 'true')
Set-Content target\wasm32-unknown-unknown\release\mycrate.js -Value $js
```

**Comment by koute** [comment]
This is something I've been thinking about fixing soon. If `cargo-web` would support generating a `.js` runtime which you'd have to manually initialize would that work for you? Basically you'd fetch and instantiate the `.wasm` file yourself; the generated runtime would only provide you with the `imports` object (to use when instantiating the `.wasm`) and an initialization function to which you'd pass the `.wasm` module you've instantiated.

(See also https://github.com/koute/cargo-web/issues/76, https://github.com/koute/cargo-web/issues/35, https://github.com/koute/cargo-web/issues/71)

**Comment by LaylConway** [comment]
Yes that would definitely work!

**Comment by koute** [comment]
Cool! I'll try to whip something up tomorrow and/or this weekend depending on how much time I have.

**Comment by koute** [comment]
This is long supported with the `--runtime` option; closing.
