### ISSUE TITLE
Building/testing a crate with features seems broken

### ISSUE THREAD

**Issue by pitdicker** [koute/cargo-web#95]
On the CI for Rand we have the following test for testing with stdweb:
```
cargo web test --target wasm32-unknown-unknown --nodejs --features=stdweb
```

Since yesterday it fails with the error from https://internals.rust-lang.org/t/help-us-test-the-breaking-bug-fix-to-cargo-features/7317:
```
error: error: cannot specify features for more than one package
```

Using `--all-features` instead works for rand.

cc @dhardy

**Comment by koute** [comment]
Hmm... looks like this is an issue with `cargo` itself. If you run this it will also generate the same error: `cargo metadata --features stdweb`

**Comment by koute** [comment]
I've created an issue here: https://github.com/rust-lang/cargo/issues/5439
