### ISSUE TITLE
Feature request: `cargo web open` command to open browser

### ISSUE THREAD

**Issue by casey** [koute/cargo-web#97]
`open https://localhost:8000` will work on MacOS. I think that `xdg-open https://localhost:8000` will work on linux.

Thanks for all your work on `cargo-web`!

**Comment by koute** [comment]
I think something like `cargo web start --open` would be more appropriate than a new subcommand.

Yeah, it should be pretty easy to add, especially since we can just copy the code from `cargo`. (More specifically `cargo doc --open` already does exactly this.)

**Comment by casey** [comment]
It might be a little confusing as a flag, since you might want to do it multiple times. I.E. `cargo web start` once, and then `cargo web open` multiple times after that.

**Comment by srenatus** [comment]
Looks like #101 resolved this?

**Comment by koute** [comment]
Yes. It's not released yet though; I'll release a new version this week.

**Comment by casey** [comment]
Sweeeeeet
